### ISSUE TITLE
Could not find the technical paper mentioned in repository.

### ISSUE THREAD

**Issue by marcemq** [worldbank/GLAD#3]
Will be nice to have the link to the technical paper by _Azevedo, J.P., and others. 2019. “Will Every Child Be Able to Read by 2030? Why Eliminating Learning Poverty Will Be Harder Than You Think, and What to Do About It.”_ 

I've looked for it at [The World Bank publications](http://documents.worldbank.org/curated/en/docsearch/document-type/620265) and could not find such paper.

**Comment by jpazvd** [comment]
Thanks for your question. Attached the latest link:  _[Azevedo, Joao Pedro; Goldemberg, Diana; Montoya, Silvia; Nayar, Reema; Rogers, Halsey; Saavedra, Jaime; Stacy, Brian William. 2021. Will Every Child Be Able to Read by 2030? Defining Learning Poverty and Mapping the Dimensions of the Challenge. Policy Research Working Paper;No. 9588. World Bank, Washington, DC. ](https://openknowledge.worldbank.org/handle/10986/35300)_
